version: '3.3'

services:

  gettogether-mongo:
    image: "mongo:4.2.6-bionic"
    container_name: gettogether-mongo
    volumes:
      - mongo-data:/var/lib/mongo/data
    ports:
      - 27017:27017

  gettogether-api:
    build: ./getTogether
    container_name: gettogether-api
    ports:
      - 8080:8080
    links:
      - gettogether-mongo
    environment:
      - MONGODB_URI=mongodb://gettogether-mongo

  gettogether-frontend:
    stdin_open: true
    build: ./get_together-frontend
    container_name: get_together-frontend
    ports:
      - 3000:3000
    links:
      - gettogether-api

volumes:
    mongo-data:
